import { Book, Member, Transaction } from "./types";

export const MOCK_BOOKS: Book[] = [
  {
    id: "b1",
    title: "The Great Gatsby",
    author: "F. Scott Fitzgerald",
    isbn: "978-0-7432-7356-5",
    genre: "Classic Fiction",
    publisher: "Scribner",
    year: 1925,
    totalCopies: 5,
    availableCopies: 3,
    description: "A story of the fabulously wealthy Jay Gatsby and his love for the beautiful Daisy Buchanan.",
    coverImage: "/images/great-gatsby-book-cover.jpg",
    addedAt: "2024-01-10",
  },
  {
    id: "b2",
    title: "To Kill a Mockingbird",
    author: "Harper Lee",
    isbn: "978-0-06-112008-4",
    genre: "Classic Fiction",
    publisher: "HarperCollins",
    year: 1960,
    totalCopies: 4,
    availableCopies: 2,
    description: "The story of racial injustice and the loss of innocence in the American South.",
    coverImage: "/images/to-kill-a-mockingbird-book.jpg",
    addedAt: "2024-01-12",
  },
  {
    id: "b3",
    title: "1984",
    author: "George Orwell",
    isbn: "978-0-452-28423-4",
    genre: "Dystopian Fiction",
    publisher: "Signet Classic",
    year: 1949,
    totalCopies: 6,
    availableCopies: 4,
    description: "A dystopian social science fiction novel and cautionary tale about the dangers of totalitarianism.",
    coverImage: "/images/1984-george-orwell-book.jpg",
    addedAt: "2024-01-15",
  },
  {
    id: "b4",
    title: "The Alchemist",
    author: "Paulo Coelho",
    isbn: "978-0-06-231500-7",
    genre: "Adventure Fiction",
    publisher: "HarperOne",
    year: 1988,
    totalCopies: 7,
    availableCopies: 5,
    description: "A philosophical novel about a young Andalusian shepherd who yearns to travel in search of a worldly treasure.",
    coverImage: "/images/the-alchemist-paulo-coelho.jpg",
    addedAt: "2024-01-18",
  },
  {
    id: "b5",
    title: "Sapiens: A Brief History of Humankind",
    author: "Yuval Noah Harari",
    isbn: "978-0-06-231609-7",
    genre: "Non-Fiction",
    publisher: "Harper",
    year: 2011,
    totalCopies: 3,
    availableCopies: 0,
    description: "A brief history of humankind from the Stone Age to the twenty-first century.",
    coverImage: "/images/sapiens-yuval-noah-harari.jpg",
    addedAt: "2024-01-20",
  },
  {
    id: "b6",
    title: "Atomic Habits",
    author: "James Clear",
    isbn: "978-0-7352-1129-2",
    genre: "Self-Help",
    publisher: "Avery",
    year: 2018,
    totalCopies: 5,
    availableCopies: 2,
    description: "An easy and proven way to build good habits and break bad ones.",
    coverImage: "/images/atomic-habits-james-clear.jpg",
    addedAt: "2024-02-01",
  },
  {
    id: "b7",
    title: "The Lean Startup",
    author: "Eric Ries",
    isbn: "978-0-307-88791-7",
    genre: "Business",
    publisher: "Crown Business",
    year: 2011,
    totalCopies: 4,
    availableCopies: 3,
    description: "How today's entrepreneurs use continuous innovation to create radically successful businesses.",
    coverImage: "/images/lean-startup-eric-ries.jpg",
    addedAt: "2024-02-05",
  },
  {
    id: "b8",
    title: "Dune",
    author: "Frank Herbert",
    isbn: "978-0-441-17271-9",
    genre: "Science Fiction",
    publisher: "Ace Books",
    year: 1965,
    totalCopies: 4,
    availableCopies: 1,
    description: "Set in the distant future amidst a feudal interstellar society, Dune tells the story of young Paul Atreides.",
    coverImage: "/images/dune-frank-herbert-novel.jpg",
    addedAt: "2024-02-10",
  },
  {
    id: "b9",
    title: "The Psychology of Money",
    author: "Morgan Housel",
    isbn: "978-0-857-19776-9",
    genre: "Finance",
    publisher: "Harriman House",
    year: 2020,
    totalCopies: 5,
    availableCopies: 4,
    description: "Timeless lessons on wealth, greed, and happiness through short stories about how people think about money.",
    coverImage: "/images/psychology-of-money-morgan-housel.jpg",
    addedAt: "2024-02-15",
  },
  {
    id: "b10",
    title: "Harry Potter and the Sorcerer's Stone",
    author: "J.K. Rowling",
    isbn: "978-0-590-35340-3",
    genre: "Fantasy",
    publisher: "Scholastic",
    year: 1997,
    totalCopies: 8,
    availableCopies: 5,
    description: "The first novel in the Harry Potter series, following a young wizard's first year at Hogwarts School.",
    coverImage: "/images/harry-potter-sorcerers-stone.jpg",
    addedAt: "2024-02-20",
  },
  {
    id: "b11",
    title: "Clean Code",
    author: "Robert C. Martin",
    isbn: "978-0-13-235088-4",
    genre: "Technology",
    publisher: "Prentice Hall",
    year: 2008,
    totalCopies: 3,
    availableCopies: 1,
    description: "A handbook of agile software craftsmanship with practical advice on writing clean, maintainable code.",
    coverImage: "/images/clean-code-robert-martin.jpg",
    addedAt: "2024-03-01",
  },
  {
    id: "b12",
    title: "The Midnight Library",
    author: "Matt Haig",
    isbn: "978-0-525-55947-4",
    genre: "Contemporary Fiction",
    publisher: "Viking",
    year: 2020,
    totalCopies: 4,
    availableCopies: 3,
    description: "A novel about regret, hope, and the choices that make us who we are.",
    coverImage: "/images/midnight-library-matt-haig.jpg",
    addedAt: "2024-03-05",
  },
];

export const MOCK_MEMBERS: Member[] = [
  {
    id: "m1",
    name: "Alice Johnson",
    email: "alice.johnson@email.com",
    phone: "+1-555-0101",
    address: "123 Maple Street, Springfield, IL 62701",
    membershipId: "LIB-2024-001",
    joinedAt: "2024-01-05",
    status: "active",
    totalBorrowed: 12,
    currentlyBorrowed: 2,
  },
  {
    id: "m2",
    name: "Bob Martinez",
    email: "bob.martinez@email.com",
    phone: "+1-555-0102",
    address: "456 Oak Avenue, Chicago, IL 60601",
    membershipId: "LIB-2024-002",
    joinedAt: "2024-01-10",
    status: "active",
    totalBorrowed: 8,
    currentlyBorrowed: 1,
  },
  {
    id: "m3",
    name: "Carol Williams",
    email: "carol.williams@email.com",
    phone: "+1-555-0103",
    address: "789 Pine Road, Naperville, IL 60540",
    membershipId: "LIB-2024-003",
    joinedAt: "2024-01-15",
    status: "active",
    totalBorrowed: 15,
    currentlyBorrowed: 3,
  },
  {
    id: "m4",
    name: "David Chen",
    email: "david.chen@email.com",
    phone: "+1-555-0104",
    address: "321 Elm Street, Evanston, IL 60201",
    membershipId: "LIB-2024-004",
    joinedAt: "2024-01-20",
    status: "suspended",
    totalBorrowed: 5,
    currentlyBorrowed: 0,
  },
  {
    id: "m5",
    name: "Emma Davis",
    email: "emma.davis@email.com",
    phone: "+1-555-0105",
    address: "654 Birch Lane, Aurora, IL 60505",
    membershipId: "LIB-2024-005",
    joinedAt: "2024-02-01",
    status: "active",
    totalBorrowed: 20,
    currentlyBorrowed: 2,
  },
  {
    id: "m6",
    name: "Frank Thompson",
    email: "frank.thompson@email.com",
    phone: "+1-555-0106",
    address: "987 Cedar Drive, Joliet, IL 60432",
    membershipId: "LIB-2024-006",
    joinedAt: "2024-02-10",
    status: "active",
    totalBorrowed: 3,
    currentlyBorrowed: 1,
  },
  {
    id: "m7",
    name: "Grace Lee",
    email: "grace.lee@email.com",
    phone: "+1-555-0107",
    address: "147 Walnut Court, Rockford, IL 61101",
    membershipId: "LIB-2024-007",
    joinedAt: "2024-02-15",
    status: "active",
    totalBorrowed: 9,
    currentlyBorrowed: 0,
  },
  {
    id: "m8",
    name: "Henry Wilson",
    email: "henry.wilson@email.com",
    phone: "+1-555-0108",
    address: "258 Spruce Way, Peoria, IL 61602",
    membershipId: "LIB-2024-008",
    joinedAt: "2024-03-01",
    status: "expired",
    totalBorrowed: 2,
    currentlyBorrowed: 0,
  },
];

export const MOCK_TRANSACTIONS: Transaction[] = [
  {
    id: "t1",
    bookId: "b1",
    memberId: "m1",
    bookTitle: "The Great Gatsby",
    memberName: "Alice Johnson",
    issueDate: "2024-11-01",
    dueDate: "2024-11-15",
    returnDate: "2024-11-14",
    status: "returned",
    fine: 0,
    finePaid: true,
  },
  {
    id: "t2",
    bookId: "b5",
    memberId: "m1",
    bookTitle: "Sapiens: A Brief History of Humankind",
    memberName: "Alice Johnson",
    issueDate: "2024-11-20",
    dueDate: "2024-12-04",
    status: "issued",
    fine: 0,
    finePaid: false,
  },
  {
    id: "t3",
    bookId: "b3",
    memberId: "m1",
    bookTitle: "1984",
    memberName: "Alice Johnson",
    issueDate: "2024-10-01",
    dueDate: "2024-10-15",
    returnDate: "2024-10-20",
    status: "returned",
    fine: 5.0,
    finePaid: true,
  },
  {
    id: "t4",
    bookId: "b8",
    memberId: "m2",
    bookTitle: "Dune",
    memberName: "Bob Martinez",
    issueDate: "2024-11-25",
    dueDate: "2024-12-09",
    status: "issued",
    fine: 0,
    finePaid: false,
  },
  {
    id: "t5",
    bookId: "b11",
    memberId: "m3",
    bookTitle: "Clean Code",
    memberName: "Carol Williams",
    issueDate: "2024-10-15",
    dueDate: "2024-10-29",
    status: "overdue",
    fine: 15.0,
    finePaid: false,
  },
  {
    id: "t6",
    bookId: "b6",
    memberId: "m3",
    bookTitle: "Atomic Habits",
    memberName: "Carol Williams",
    issueDate: "2024-11-10",
    dueDate: "2024-11-24",
    status: "overdue",
    fine: 8.0,
    finePaid: false,
  },
  {
    id: "t7",
    bookId: "b2",
    memberId: "m3",
    bookTitle: "To Kill a Mockingbird",
    memberName: "Carol Williams",
    issueDate: "2024-11-28",
    dueDate: "2024-12-12",
    status: "issued",
    fine: 0,
    finePaid: false,
  },
  {
    id: "t8",
    bookId: "b10",
    memberId: "m5",
    bookTitle: "Harry Potter and the Sorcerer's Stone",
    memberName: "Emma Davis",
    issueDate: "2024-11-15",
    dueDate: "2024-11-29",
    status: "overdue",
    fine: 12.0,
    finePaid: false,
  },
  {
    id: "t9",
    bookId: "b4",
    memberId: "m5",
    bookTitle: "The Alchemist",
    memberName: "Emma Davis",
    issueDate: "2024-11-28",
    dueDate: "2024-12-12",
    status: "issued",
    fine: 0,
    finePaid: false,
  },
  {
    id: "t10",
    bookId: "b7",
    memberId: "m6",
    bookTitle: "The Lean Startup",
    memberName: "Frank Thompson",
    issueDate: "2024-11-20",
    dueDate: "2024-12-04",
    status: "issued",
    fine: 0,
    finePaid: false,
  },
  {
    id: "t11",
    bookId: "b9",
    memberId: "m7",
    bookTitle: "The Psychology of Money",
    memberName: "Grace Lee",
    issueDate: "2024-10-20",
    dueDate: "2024-11-03",
    returnDate: "2024-11-05",
    status: "returned",
    fine: 2.0,
    finePaid: true,
  },
  {
    id: "t12",
    bookId: "b12",
    memberId: "m2",
    bookTitle: "The Midnight Library",
    memberName: "Bob Martinez",
    issueDate: "2024-09-01",
    dueDate: "2024-09-15",
    returnDate: "2024-09-14",
    status: "returned",
    fine: 0,
    finePaid: true,
  },
];
